### ISSUE TITLE
Add AMF & WordPress AMF as dependencies to the Media module

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-media#100]
We need to include the AMF and WordPress AMF as dependencies in the Altis Media module

Acceptance criteria:
- [x] Enable or Disable via altis-config with default off
- [x] Integrate any settings within the altis-config
- [x] Documentation of AMF

**Comment by johnbillion** [comment]
Putting this here as a potential discussion point: https://github.com/humanmade/asset-manager-framework/issues/26
