### ISSUE TITLE
Add ability to delete assets from the global library

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-media#104]
We want to be able to delete assets from the global library within the global library.

Scenario 1
Given: I am on a local site
When: I view the details of an asset sourced from the global library
Then: I should not be able to delete the asset
And: I should have a link to view the details of the asset in the global library

Scenario 2
Given: I am on the global library as a author (or higher) on the global site
When: I delete a media file
Then: I should get a warning that the file could be used in other places
And: If accepted, it should not be available on the local sites where it was being used

When the asset is not available, this acts the same as deleting a regular asset in WordPress (i.e. links or embeds may break).

**Comment by johnbillion** [comment]
Related AMF issue: https://github.com/humanmade/asset-manager-framework/issues/13
