### ISSUE TITLE
Load more than first page of images/pagination

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-media#105]
This is more an issue with the [AMF WordPress](https://github.com/humanmade/amf-wordpress) plugin itself, but there may be defaults or a filter within the code that we could use as a default. Needs investigation.

Acceptance criteria:
* [ ] When viewing the media library with over 100 images, when I scroll, more images should load in

**Comment by johnbillion** [comment]
By default when the media library loads it will run multiple Ajax requests if necessary to show enough media files to cause the screen to start to scroll. It does this via multiple Ajax requests.

This works as expected in AMF and I can't see a reason it wouldn't work in AMF-WP, which [supports the correct query parameters](https://github.com/humanmade/amf-wordpress/blob/85375ce33771b41682bb528a5cd2174a68413126/inc/class-provider.php#L89). Neither of these libraries make adjustments to how the media modal fetches attachments .

Might this be an issue with the justified media library in Smart Media?

**Comment by johnbillion** [comment]
Also this is of interest: https://core.trac.wordpress.org/ticket/50105

**Comment by roborourke** [comment]
I can't reproduce this, all loads in properly from what I can see. We can reopen it again later if it's observed again or we find a repeatable test case.
