### ISSUE TITLE
Allow both global assets as well as local assets

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-media#107]
We would potentially like to support both global assets as well as local assets, much like Multisite Global Media.

![Multisite Global Media screenshot](https://camo.githubusercontent.com/7b178f52a72f9c6ae5226d3d3d41275a55a816338b837753ecf5200970b306e9/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3538303636393561393565343262366335626161616339342f62643763383061372d333866652d346264652d626334372d643333386238656139323664)

This may be dependent upon #103

**Acceptance Criteria:**

~Scenario 1
Given: I have created and edited a media asset
When: I upload it to the global media library from my local website
Then: The same should be made available to our organization's global network as a singular attachment
And: Any further edits to this file should get updated in the central library seamlessly in real time~
This scenario is covered by #123 

Scenario 2:
Given: I am working in a subsite 
When: I want to use an edited picture that is in the global library 
Then: I should be able to find it the media library such that it can be copied to the local media library
 
Scenario 3:
Given: There is some meta data (alt text, caption, description) associated with a file 
When: I use that media file in another location
Then: The existing meta data should be carried over

**Comment by roborourke** [comment]
If WP can be used as a source then potentially allowing multiple providers as outlined in #103 could be the solution to this as well.

There's a couple of things we'd potentially need to do:

- Support multiple providers
- Update AMF WP to accept source URL as a provider constructor argument or value that can be set after initialising the provider
- Update AMF WP to support image resizing service config
- Update Smart Media to handle external Tachyon source

**Comment by roborourke** [comment]
Started working on @shadyvb's multiple providers branch and has code to allow local uploads. I think I can get a workable solution in a few days now based on that.

**Comment by johnbillion** [comment]
Thought: If multiple providers support file uploads, how is it determined where a new file upload gets routed?

**Comment by rmccue** [comment]
@johnbillion The upload flow is covered in https://github.com/humanmade/altis-media/issues/123

**Comment by roborourke** [comment]
This is an issue for supported local uploads too really.

One approach is to just upload to the first or default provider, and then provide buttons / options to copy or sync to another provider.

The approach I'm currently investigating is the following:

- Media admin
  - Have additional sub menu items for each provider eg. "Local Media", "Global Media", "Unsplash" etc...
  - Each sub menu section or page will persist a query string or post variable for determining the provider to use
- Media modal
  - Default to local or first available provider
  - Provide buttons to copy to other providers
