### ISSUE TITLE
Recognition and Alt search fields even when not searching media

### ISSUE THREAD

**Issue by tareiking** [humanmade/altis-media#108]
I noticed that all ES searches are getting the `rekognition_labels` and `alt` [search fields](https://github.com/humanmade/altis-media/blob/master/inc/namespace.php#L176) added even when not specifically searching media.

Is this intentional? IE: Searching page/posts in WP Admin and investigating with Query Monitor shows these search fields under the ElasticPress tab.

Just curious if we can/should limit the inclusion of these to only run on media related searches?

**Comment by roborourke** [comment]
They don't do any harm being there, I think later versions of ElasticPress will split the fields up by post type but the queries are not performant if you have a lot of post types.

It's intentional at any rate and won't impact on anything when you're not searching media.

**Comment by tareiking** [comment]
Thanks @roborourke super useful info. Happy to close the issue in that case. TY.
