### ISSUE TITLE
Large media files (~ >100mb) throw error after uploading

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-media#109]
**Description of issue**
When large media files are uploaded (roughly > 100MB, approx) an error message displays. The media file is uploaded but requires a refresh to see it in the media library.

Steps to reproduce:
1. Upload a large media file (a particularly large PDF file or a raw video file)
2. wait for the upload to complete
3. see error

![Screen Shot 2021-03-30 at 3 18 11 PM](https://user-images.githubusercontent.com/991511/113058745-c48c7680-916b-11eb-842f-3df8cf304e9a.png)

(For reference, the files I tested with are a 154MB pdf file and a 204MB mp4 file)

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
I think this might be down to timeouts if it was taking more than 30 / 60 seconds... Might have been reported already, I'll take a look.

**Comment by jazzsequence** [comment]
I don't _think_ it was taking that long to upload but I can test again. This is less of an issue, though, since the file does upload and the message displayed actually indicates that.

**Comment by jazzsequence** [comment]
Not able to consistently reproduce. May have been related to an older version of `smart-media` in `extra-packages`. Closing.
