### ISSUE TITLE
Large image size displays incorrect dimensions in smart media modal

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-media#110]
The correct dimensions do not display in the media modal for the large image size. The large image size does not change after updating dimension settings and doesn't even reflect the default of 1024x1024. 

This appears to be the case _only_ for the large image size, and the large image size is _always_ the same as the "medium large" image size (640x640).

Steps to reproduce:
1. Update the dimensions of one of the large image size
2. Return to the Media Library
3. Upload a new image
4. Click the new image to edit it
5. The updated dimensions do not display

**Expected behavior:**
The correct large dimensions display in the modal 

Updated Large size settings
![Screen Shot 2021-03-31 at 12 16 43 PM](https://user-images.githubusercontent.com/991511/113191829-42f42180-921b-11eb-8c95-d996574479bf.png)

Media modal for image (uploaded after change)
![Screen Shot 2021-03-31 at 12 17 01 PM](https://user-images.githubusercontent.com/991511/113191857-4d162000-921b-11eb-989f-dffc253d0cbf.png)

Post with the image set to Large size (updated dimensions are used)
![Screen Shot 2021-03-31 at 12 17 52 PM](https://user-images.githubusercontent.com/991511/113191921-60c18680-921b-11eb-9221-6ffe8a443c12.png)

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
Hmm, not sure if this is something to fix directly - it's weird but it's being capped by the theme's `$GLOBALS['content_width']` setting. Gonna check how it behaves without smart media.

**Comment by jazzsequence** [comment]
Confirmed, this ties to the content width setting. It's overridden if you define a different content width. 

Without Smart Media, there doesn't appear to be an easy way (outside of the code) to use the "large" image size (it's not visible, at any rate) and inserting an image defaults to inserting the full size.

Closing this, but perhaps we should add some documentation about this, specifically.
