### ISSUE TITLE
Better messaging when AWS Rekognition is non operational

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-media#112]
On a local Altis development environment, AWS Rekognition appears to be non operational. This results in either an infinite spinner for image labels or a plain blank meta box. It would be better if there was an informational message shown in place of the labels when Rekognition can't do its thing.

## Screenshots

<img width="292" alt="" src="https://user-images.githubusercontent.com/208434/114456189-dd217580-9bdc-11eb-88d5-46ba0c2437d0.png">

<img width="295" alt="" src="https://user-images.githubusercontent.com/208434/114456192-ddba0c00-9bdc-11eb-8568-c7075bc9c1be.png">

**Comment by roborourke** [comment]
Would this also fix your other issue here in your view? https://github.com/humanmade/altis-local-server/issues/273

We could close that one out and handle it here instead, it looks like a duplicate to me.

**Comment by johnbillion** [comment]
Ah I forgot about that one.

**Comment by johnbillion** [comment]
Closed the other issue.
