### ISSUE TITLE
Select button is disabled even after selecting a media file to insert

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-media#118]
The operation is a bit clunky. When I select a media file the select button doesn't immediately get enabled.

I have to select, deselect and reselect the file to see the "Select" button at the bottom show up. 

See the screenshot below where even though I have selected a media file to insert the "Select" button doesn't get enabled immediately. 

![image.png](https://images.zenhubusercontent.com/5db35a48a7e95f000179f54e/1b9dbcf3-526b-454b-ab87-be86daad237d)

**Comment by roborourke** [comment]
Unable to reproduce any more, this was likely an intermittent issue during other changes to platform-test.
