### ISSUE TITLE
Version control in the Media Library

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-media#119]
**Acceptance Criteria:**
Given: A user has created a new version of a media file already in use on the global library
When: They do not have the permissions to update/modify/delete an old version of the file in the global library
And: They want to indicate any other user to use a new version 
Then: They should should be able to leave a comment on the old version of the file that " A new version of this file exists at....."

**Comment by rmccue** [comment]
Closing as won't do for now.
