### ISSUE TITLE
Add Network Media Library

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-media#14]
https://github.com/humanmade/network-media-library

**Comment by roborourke** [comment]
Additionally it'd be good to handle automatic creation of the media site and optional configuration override.

**Comment by rmccue** [comment]
Doesn't seem like we've needed this recently, but let's reopen if we have a need.

**Comment by roborourke** [comment]
There have been multiple requirements for this exact feature on at least 3 client projects so I’m hesitant to rule it out immediately. Especially given that it’ll make integrating asset management platforms more straightforward.
