### ISSUE TITLE
Warnings on platform-test from gaussholder

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-media#154]
On platform-test, getting the following warnings:
<img width="1266" alt="Screen Shot 2021-07-08 at 13 41 07" src="https://user-images.githubusercontent.com/21655/124923331-39d0d880-dff2-11eb-9f40-e244bdc22148.png">

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
Closing as stale. We can look again but my sense is that gaussholder is not used much
