### ISSUE TITLE
Select button greyed out in Media library until a second video is selected

### ISSUE THREAD

**Issue by Hazlitte** [humanmade/altis-media#198]
I have developed an integration of YouTube videos into the Media Library using AMF.

With my integration I am having a problem where if I use the video block to insert a Youtube video the Media Library is displayed but the 'Select' button is disabled for the first video I highlight.  When I highlight a second video the 'Select' button is enabled. 

Disabling 'smart-media' solves this bug.

Steps to reproduce:
1.  Add a Video block to a post
2.  Choose to insert from the Media Library
3.  Instead of 'Local Media' choose 'YouTube'
4.  Select a video - The 'Select' button is disabled
5.  Select a second video - The 'Select' button is now enabled

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
I don't have the AMF provider referenced here to test with so it would be good to know if this happens with the regular video block and normal video files too.

**Comment by roborourke** [comment]
Should be fixed by https://github.com/humanmade/smart-media/pull/167 - released in 0.4.2 and 0.3.12
