### ISSUE TITLE
Using 'Remove featured image' whilst editing a post with a saved featured image breaks the 'Set featured image' functionality.

### ISSUE THREAD

**Issue by Hazlitte** [humanmade/altis-media#204]
Steps to reproduce:

- Edit a post with a saved image
- Click on ‘Remove featured image’
- The image is no longer displayed
- Click on ‘Set featured image’
- Nothing happens, the ‘Set featured image’ functionality is broken and the following error is displayed in the console: 'Uncaught TypeError: Cannot read properties of undefined (reading 'match')'

<img width="525" alt="Screenshot 2021-12-13 at 12 56 19" src="https://user-images.githubusercontent.com/5174233/145820390-2d0909f6-2ca1-490b-8b69-dd716dff195c.png">

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
@Hazlitte you can run a `composer update -W` to get the latest smart media with the fix now.

**Comment by kadamwhite** [comment]
Confirmed this was a CI deploy failure on the Smart Media plugin side, I believe @roborourke is looking into it

**Comment by roborourke** [comment]
Phew, resolved again - switched to GitHub actions for releases

**Comment by Hazlitte** [comment]
I tested today and your update has resolved the bug I had.  Fantastic, thank you 🙏
