### ISSUE TITLE
Gaussholder image not in DB

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-media#23]
When uploading an image and with teh image sizes config, I don't get the image data in the post meta.

**Comment by joehoyle** [comment]
Pretty sure this is happening in local-server only, because the local-server doesnt have access to do loopback requests, which Gaussholder will try to do with used with Tachyon.

**Comment by joehoyle** [comment]
Will be fixed by https://github.com/humanmade/altis-local-server/pull/30

**Comment by roborourke** [comment]
Closing as above PR merged.
