### ISSUE TITLE
Rekognition not falling back to supported region

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-media#27]
Seems the update we did @joehoyle isn't working properly, it's still trying to access the S3 object in unsupported regions.

**Comment by joehoyle** [comment]
We need to get this fixed in v2

**Comment by rmccue** [comment]
@joehoyle Are you looking into this or shall someone else pick it up?

**Comment by joehoyle** [comment]
@rmccue I won't be able to get to it today, so if anyone else has time to pick up 👍

**Comment by roborourke** [comment]
PR open at https://github.com/humanmade/aws-rekognition/pull/16

**Comment by joehoyle** [comment]
We need to:

- [ ] Publish a new release of rekognition
- [ ] Update version contsraint for this module
