### ISSUE TITLE
Add docs for registering image sizes

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-media#3]
We don't currently have any documentation on registering image sizes at all, so we should document how to register image sizes and use them.

In addition, we should document Tachyon parameters and settings.

**Comment by rmccue** [comment]
@joehoyle to rewrite this ticket to clarify intent.

**Comment by roborourke** [comment]
Tachyon parameters have been documented now, so just image sizes remaining. It's an important part of the CMS and ties into the expected behaviours of the CMS and how it affects cropping.

We should document:

- `add_image_size()` - when (eg. `after_setup_theme`) and how to call it with examples
- the `image_size_names_choose` filter to control which image sizes are selectable in the CMS
- guidance on using an array eg. `[ 300, 200 ]` to define the size on demand eg. with `wp_get_attachment_image_src()`
