### ISSUE TITLE
Upstream bug in Tachyon leads to 404s

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-media#30]
https://github.com/humanmade/tachyon-plugin/issues/43

Acceptance criteria:

- [ ] Images with names like `image-300x300.jpg` can be uploaded and processed successfully by tachyon

**Comment by joehoyle** [comment]
This isn't going to make it in v2 I think.

**Comment by roborourke** [comment]
For this we could perhaps detect that pattern in file names on upload and strip the dimensions before saving to disk. I think that should work, otherwise we need to be able to factor in the original file name before running content filters.

**Comment by roborourke** [comment]
Got a PR for a CLI migration command here https://github.com/humanmade/tachyon-plugin/pull/63

**Comment by roborourke** [comment]
Taken a different approach here and providing a migration command directly with Altis. See #93

**Comment by roborourke** [comment]
Going to close this issue out as we have a solution now. It is being handled separately for affected clients.
