### ISSUE TITLE
darylldoyle/safe-svg has been downgraded in v16

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-media#318]
Using Altis v15, `darylldoyle/safe-svg` is at version 2.0.3.

Upgrading to Altis v16 has caused it to be downgraded to 2.0.1.

Is this intentional? Seems like #316 has not been ported to v16.

**Comment by mikelittle** [comment]
No. not intentional. I'll sort it.

**Comment by mikelittle** [comment]
@johnbillion That change has been back-ported and a new release should be generated shortly.
