### ISSUE TITLE
Encoding issues in block editor with image URLs containing @ / unicode

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-media#67]
Seems this problem keeps rearing it's head!

<img width="1160" alt="screenshot-20200226-165140" src="https://user-images.githubusercontent.com/23417/75371209-400f5a80-58be-11ea-8a81-5b1ccc617231.png">

In an image with an `@` in the name being uploaded via the image block the above error is shown. This is likely because of double escaping going on, either at the JS level or a combination of both PHP and JS.

---------

Acceptance criteria:

- [ ] Images URLs are not double encoded by the smart-media plugin
- [ ] Image names with unicode characters work as expected in the image cropper and gutenberg blocks

**Comment by roborourke** [comment]
Confirmed this will happen when `encodeURI` is run twice on `@` - result is `%40` then `%2540`.

**Comment by abhishek-kaushik** [comment]
Not able to replicate the issue on [https://platform-test.aws.hmn.md/?p=242&preview=true](https://platform-test.aws.hmn.md/?p=242&preview=true) and on uploading an image with unicode character onto media library as well : [https://platform-test.aws.hmn.md/wp-admin/upload.php?item=245](https://platform-test.aws.hmn.md/wp-admin/upload.php?item=245)

**Comment by roborourke** [comment]
This seems to be resolved now. Closing out for now, might've been specific to how a GB block was implemented.
