### ISSUE TITLE
Option not to add the detected tags into Alt when inserting media to posts

### ISSUE THREAD

**Issue by ShinichiNishikawa** [humanmade/altis-media#68]
It would be useful if we can configure that CMS doesn't add the detected tags to the "alt" attribute of inserted media in posts. 

One example is to use this in non-English websites. We don't want to deliver English words to for example a Japanese screen reader user. 

--------------

Acceptance criteria:

- [ ] If the current site language is not english eg. locale does not start `en` then don't update image the alt text automatically

See the filter example in this comment for how https://github.com/humanmade/altis-media/issues/68#issuecomment-547943849

**Comment by kucrut** [comment]
Looks like currently there's no way to toggle alt text modification on/off in aws rekognition plugin, because unlike the other filters (`*.labels`, `*.faces`, etc), `hm.aws.rekognition.alt_text` is _not_ a toggle filter.

@roborourke Do you think we should introduce a new filter for this?

**Comment by roborourke** [comment]
@kucrut yeah the filter I provided above does the job but it's not simple or obvious to use. Can you add the filter to humanmade/aws-rekognition and then update this repo to provide a config option to set whether you want automatic alt text population on?

**Comment by PriyaBhatia0210** [comment]
Wont do this right now.
