### ISSUE TITLE
Image crop does not work on images with japanese/unicode characters in the filename

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-media#91]
Steps to reproduce:

**Cropping the image**
1. Add an image with unicode characters in the filename to a post 
2. Click the crop tool button
3. Zoom in/out to crop the image
4. Click Apply

**Changing the aspect ratio**
1. Add an image with unicode characters in the filename to a post
2. Click the Crop tool button
3. Click the Aspect Ratio button
4. Click Apply

**Changing the aspect ratio and cropping**
1. Add an image with unicode characters in the filename to a post
2. Click the Crop tool button
3. Click the Aspect Ration button
4. Zoom in/out to crop the image
5. Click Apply

In each of the above cases an error displays in the bottom left of the screen:
`Could not edit image. Unable to get meta information for file.`

## Expected behavior

The image scales/crops in the block editor.

## Screenshots

Screencap shows the issue cropping and changing the aspect ratio
https://www.dropbox.com/s/0exzjpptfr0mvyi/altis-v5-image-aspect-ratio-crop.mov?dl=0

Screencap shows the issue _not_ occurring with files with latin characters in the filename, but displaying the issue with an image with unicode characters in the filename.
https://www.dropbox.com/s/1osehy77z55itt4/altis-v5-qa-unicode-japanese-characters-aspect-ratio-crop.mov?dl=0

## Acceptance criteria

- [ ] ...

**Comment by roborourke** [comment]
Given this is the image block editor we can narrow it down, hopefully it's not an upstream WP bug - that's pretty unlikely.

We can test this by turning off the media module and trying to reproduce it first, then proceed with S3, Tachyon & smart media switched switched off and then reintroduce them.

**Comment by roborourke** [comment]
We store image URLs as URL encoded which WP doesn't expect so this was breaking any time `wp_image_file_matches_image_meta()` was used.
